CREATE DATABASE contasLT;


USE contasLT;

DROP TABLE IF EXISTS bandeira;

CREATE TABLE bandeira (
idBandeira SMALLINT IDENTITY CONSTRAINT pk_idBandeira PRIMARY KEY(idBandeira),
Cor VARCHAR(10) NOT NULL,
Valor MONEY NOT NULL
);

CREATE TABLE contas (
idRegistro INT IDENTITY CONSTRAINT pk_idRegistro PRIMARY KEY(idRegistro),
EInjetada INT NOT NULL,
EAtiva INT NOT NULL,

);